### ISSUE TITLE
Leverage KeystoneJS backend

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [vidalab/vida#37]
Can Vida be used to create Custom Pages on KeystoneJS ?
References
https://www.keystonejs.com/
https://github.com/keystonejs/keystone/blob/master/docs-next/pages/roadmap.mdx
https://www.keystonejs.com/blog/roadmap-update

**Comment by dnprock** [comment]
Hello,

Looks like you can add custom pages with KeystoneJS.

https://www.keystonejs.com/keystonejs/app-admin-ui/#pages

You can install vidajs into your application and create a page.

```
yarn install vidajs
```

Here's an example of using vidajs in your own application:

https://blog.vida.io/2020-create-a-machine-learning-app-with-mljs-and-redwoodjs/
